server:
  port: 8080
  servlet:
    context-path: /draw
    
spring:
  config:
    activate:
      on-profile: dev  
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: user01
    url: jdbc:mysql://127.0.0.1:8889/fisa?useSSL=false&allowPublicKeyRetrieval=true
    username: user01
    
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true 
    
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp  
---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: scott
    url: jdbc:oracle:thin:@127.0.0.1:9998:xe
    username: tiger
  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true 
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp